name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v3

#       - name: Login to docker
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKER_LOGIN }}
#           password: ${{ secrets.DOCKER_PASSWORD }}

#       - name: Build and push client
#         uses: docker/build-push-action@v3
#         with:
#           context: ./Client
#           push: true
#           tags: egoraugust/rusi4:client

#       - name: Build and push rtmp server
#         uses: docker/build-push-action@v3
#         with:
#           context: ./Server/rtmp
#           push: true
#           tags: egoraugust/rusi4:rtmp

#       - name: Build and push API server
#         uses: docker/build-push-action@v3
#         with:
#           context: ./Server/serverpy
#           push: true
#           tags: egoraugust/rusi4:api
  deploy:
    runs-on: ubuntu-latest
    
    env:
      DOCKER_LOGIN: ${{secrets.DOCKER_LOGIN}}
      DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
    steps:
      - name: ssh client
        run: |
          eval $(ssh-agent -s)
          echo "${{secrets.PRIVATE}}" | tr -d '\r' | ssh-add -
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh -o StrictHostKeyChecking=no root@77.253.96.53 "docker --version"
          
#          ssh -o StrictHostKeyChecking=no root@77.253.96.53 "echo $DOCKER_PASSWORD | docker login -u $DOCKER_LOGIN --password-stdin; docker compose pull; docker compose up"
#         uses: appleboy/ssh-action@master
#         with:
#           host: 77.253.96.53
#           username: root
#           key: ${{secrets.PRIVATE}}
#           script: whoami
         
