name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build client
      run: docker build ./Client --tag client-image:$(date +%s)
    - name: Login to docker
      run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_LOGIN --password-stdin
    - name: Log
      run: docker ps -a
